### ISSUE TITLE
Problems with `serde_json` dependency

### ISSUE THREAD

**Issue by itamarst** [anweiss/cddl#103]
Hi,

I'm wrapping your library for Python, and initial setup failed to build:

```
  error: expected item, found `"serde_json requires that either `std` (default) or `alloc` feature is enabled"`
   --> /home/itamarst/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.69/src/features_check/error.rs:1:1
    |
  1 | "serde_json requires that either `std` (default) or `alloc` feature is enabled"
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected item
```

I imagine this is a missing feature flag in the `serde_json` dependency in `Cargo.toml`. I can workaround it locally by explicitly adding `serde_json` as a dependency, but I assume this is something that will impact other people.

**Comment by anweiss** [comment]
hey @itamarst, how are you including the `cddl` crate as a dependency in your `Cargo.toml`? The `serde_json` dependency is included when you compile the `cddl` crate using the default features.

**Comment by anweiss** [comment]
Thanks @itamarst. Indeed, it looks like with the new default `resolver = "2"` behavior in the 2021 edition, the build will fail unless you explicitly declare the `serde_json` dependency with the `std` feature as you have done. This is an easy fix on my end. Will push shortly.
