### ISSUE TITLE
.feature not active in the online validator

### ISSUE THREAD

**Issue by chrysn** [anweiss/cddl#108]
The CDDL of [the core-href draft](https://datatracker.ietf.org/doc/html/draft-ietf-core-href-09) currently does not validate in the online service unless the `.feature` is removed. Same goes for the `JC<>` example.

Docs say that .feature is supported and on by default; it appears that it is not on [on the web service](https://cddl.anweiss.tech/) because it gives errors like:

> expected rule identifier followed by an assignment token '=', '/=' or '//='

Could that be enabled for the web service?

(By the way, the README still calls the spec for .feature `draft-ietf-cbor-cddl-control`; it has been promoted to [RFC 9165](https://datatracker.ietf.org/doc/html/rfc9165) since then).

**Comment by anweiss** [comment]
This has been fixed
