### ISSUE TITLE
CBOR validation for type choice in array

### ISSUE THREAD

**Issue by tomachristian** [anweiss/cddl#116]
Using the latest version at this point in time: `0.9.0-beta.1`.

I am having a problem with validating CBOR `[18]` (hex: `9F12FF` - regardless of definite/indefinite array) against CDDL `tester = [18/12]` which should be valid.

But I am getting:
```
failed: error validating type choice at cbor location : expected value 12, got Array([Integer(Integer(18))])
```

and validating CBOR `[12]` (hex: `9F0CFF`) against the same CDDL also yields:

```
failed: error validating type choice at cbor location /0: expected value 18, got Integer(12)
error validating type choice at cbor location : expected value 12, got Array([Integer(Integer(12))])
```

but validating CBOR `[12]` and `[18]` against CDDL `tester = [18//12]` works. 

According to the specification type choices should have worked, am I mistaken or is this something that is currently not supported in this package?

Thank you for your great work!

**Comment by anweiss** [comment]
Thanks for reporting @tomachristian! Indeed this is a bug as I have repro'd on my end. Will take a look at this.

**Comment by anweiss** [comment]
@tomachristian fixed in #117 and will be included in the `0.9.0` release.

**Comment by tomachristian** [comment]
Thank you @anweiss! I will have a try on it. I have quite a large protocol described with lots of CDDL and I am currently using the "official" gem for validating CDDL (the one mentioned from the spec), but it has lots of bugs and is outdated... I really really want to use your validator instead, so I will have another try with it, would you mind if I come back with other bugs? :)

**Comment by anweiss** [comment]
Sounds great!! Yes, no problem at all. The more feedback and bug reports, the better. I've been maintaining this crate myself for a few years now and only recently has there been more traction with CDDL, and thus, this crate has garnered more interest from folks in the community.

**Comment by tomachristian** [comment]
CBOR is getting traction, so I think that is why CDDL is recently getting the same as well

**Comment by tomachristian** [comment]
Hello @anweiss!

I checked the fix and it works for the specific scenario outlined above, but there are still problems with CDDL

```
tester = [$vals]
$vals /= 18
$vals /= 12
```
_(Also tried without `tester=[$vals]`, just with `tester=$vals` to same effect (of course I updated the CBOR as well by stripping out the array begin/end)_

against the same input CBOR as above. The error message is similar to the previous one:

```
failed: error validating at cbor location : expected type $vals, got Integer(Integer(18))
```

So I would say that this problem still exists with a similar effect even though the cause here might be different.

PS: If you'd like, you can write some smoke tests and I can provide a lot of such scenarios (that would also protect the software from regressions).

**Comment by anweiss** [comment]
Also a bug. Will fix.
