### ISSUE TITLE
Group choices parsing error

### ISSUE THREAD

**Issue by tomachristian** [anweiss/cddl#120]
```
tester = $$vals
$$vals //= 18
$$vals //= 12
```
gives a `error parsing CDDL: incremental parsing error`, also
```
tester = $$vals
$$vals //= ( 18 )
$$vals //= ( 12 )
```
gives a `error parsing CDDL: incremental parsing error`
```
tester = $$vals
$$vals //= ( 18 , )
$$vals //= ( 12 , )
```
works (although unable to validate due to https://github.com/anweiss/cddl/issues/116#issuecomment-1100578210).

If I read the specification correctly, a `type` should be able to be coerced into a `group` (with one `grpent`) during semantic analysis and/or during validation (if needed). Or the other way around: everything is a group until it is not: trying to coerce it to a type and checking if it can be.

**Comment by anweiss** [comment]
Good catch @tomachristian. Will fix.

**Comment by anweiss** [comment]
Still some issues per https://github.com/anweiss/cddl/pull/121#issuecomment-1109507486.
