### ISSUE TITLE
.size control produces unexpected errors

### ISSUE THREAD

**Issue by roman-kashitsyn** [anweiss/cddl#126]
The [CDDL spec](https://datatracker.ietf.org/doc/html/rfc8610#section-3.8.1) says:

> When applied to an unsigned integer, the ".size" control restricts
   the range of that integer by giving a maximum number of bytes that
   should be needed in a computer representation of that unsigned
   integer.  In other words, "uint .size N" is equivalent to
   "0...BYTES_N", where BYTES_N == 256**N.

>     audio_sample = uint .size 3 ; 24-bit, equivalent to 0...16777216

Using version `0.9.0-beta.1`:

The contents of `size.cddl`
```cddl
start = Record
Record = {
  id: Id
}
Id = uint .size 8
```

```
$ echo '{ "id": 5 }' | cddl validate --cddl size.cddl --stdin
[ERROR] Validation from stdin failed: error validating at JSON location /id: expected value .size 8, got 5
```

I get similar obscure errors when I apply the `.size` control to the `bytes` type.

**Comment by anweiss** [comment]
Fixed in #127
