### ISSUE TITLE
Unexpected linter failure in VSCode for range definition: expected rule identifier followed by an assignment token '=', "/=" or "//="

### ISSUE THREAD

**Issue by whimboo** [anweiss/cddl#145]
When having the following definition on its own the plugin shows a linting failure as given in the summary:

```
ij-uint = 0..9007199254740991
```

But when I add the following it's all fine.

```
ij-uint = 0..9007199254740991
ij-nint = -9007199254740991..-1
ij-int = -9007199254740991..9007199254740991
```

It's not clear to me why the first example is actually broken.

**Comment by whimboo** [comment]
Note that the above definitions come from https://www.rfc-editor.org/rfc/rfc8610#appendix-E.

**Comment by anweiss** [comment]
Did a bit of digging here and the actual error under the hood is as follows:

```
error: lexer error
  ┌─ input:1:12
  │
1 │ ij-uint = 0..9007199254740991
  │            ^^ number too large to fit in target type
```

... which seems to be due to the way wasm-bindgen is parsing the 9007199254740991 into a `usize`. For whatever reason it thinks it's too big.
