### ISSUE TITLE
Regression: failure to validate CBOR in zero-occurrence case (JSON works fine)

### ISSUE THREAD

**Issue by itamarst** [anweiss/cddl#148]
Consider this schema:

```
response = {
    "success": bool,
    "data": {* label: [* tstr]}
}
label = tstr
```

You can have zero labels, which validates fine as JSON:

```json
{"success": true, "data": {}}
```

Or one label, also validates fine as JSON:

```json
{"success": true, "data": {"hello": ["world"]}}
```

When generating CBOR with Python's `cbor2` for equivalent CBOR serializations, `one.cbor` validates just fine. `zero.cbor` fails to validate, however:

```
[ERROR] Validation of "zero.cbor" failed: error validating at cbor location /"data": map requires entry key of type label
```

CBOR files are in following zip:

[cbor.zip](https://github.com/anweiss/cddl/files/9787665/cbor.zip)

**Comment by itamarst** [comment]
Changing the schema to:

```
response = {
    "success": bool,
    "data": {0* label: [* tstr]}
}
label = tstr
```

fixes it, as a workaround (and suggestion for what the bug is).

**Comment by anweiss** [comment]
Thanks @itamarst. I see the issue. Will push up a fix.
