### ISSUE TITLE
Array validation doesn't work for records

### ISSUE THREAD

**Issue by ericseppanen** [anweiss/cddl#25]
Array validation doesn't seem to work as expected when the array contains a non-homogenous "record" (fixed length list using different types at different indices).

If I create the following CDDL:
```
human = [
  age: int,
  name: tstr,
]
```
I expect that this will only validate an input list with two elements [integer, string] in order.  However, the current code will successfully validate the following (incorrect) JSON inputs:
```
["Bob", 43]
```
or
```
[44, 45, "Carol", "Chuck"]
```
It appears that the code is iterating through the group checking that somewhere in the input list there is a value of the correct type; it fails to enforce that there are the right number of elements and that elements come in the expected order.

This problem exists in CBOR validation as well.

**Comment by anweiss** [comment]
Good catch thanks @ericseppanen. Will get a fix out for this

**Comment by anweiss** [comment]
@ericseppanen I see you've already been making the necessary changes. Feel free to push up a PR when you're ready. Cheers!

**Comment by anweiss** [comment]
#61 fixes this issue.
