### ISSUE TITLE
Choice operator not parsed correctly in 0.5.2

### ISSUE THREAD

**Issue by ericseppanen** [anweiss/cddl#41]
The parsing of CDDL input `foo = (int / float)` changed in release 0.5.2.  The choice operator no longer seems to work as intended.

Reading through the rfc, the only place the `/` operator is allowed is here:
```text
type = type1 *(S "/" S type1)
```
So I would expect the resulting ast to contain a `Type` with two `Type1` elements in `type_choices`.  This is what I see in 0.5.1.

In 0.5.2 I am seeing something different: a `Group` with one `GroupChoice` containing two `GroupEntry` elements.  I don't think that's right; it's what one would expect if I had specified `foo = (int, float)`.

In fact, that's probably a better way to demonstrate the problem: the ast for `(int, float)` is the same as for `(int / float)`.

**abbreviated ast from 0.5.1**
```text
Type {
    type_choices: [
        Type1 {
            type2: Typename {
                ident: Identifier {
                    ident: "int",
                    socket: None,
                },
                generic_arg: None,
            },
            operator: None,
        },
        Type1 {
            type2: Typename {
                ident: Identifier {
                    ident: "float",
                    socket: None,
                },
                generic_arg: None,
            },
            operator: None,
        },
    ],
},
```

**abbreviated ast from 0.5.2**
```text
Group {
    group_choices: [
        GroupChoice {
            group_entries: [
                (
                    TypeGroupname {
                        ge: TypeGroupnameEntry {
                            occur: None,
                            name: Identifier {
                                ident: "int",
                                socket: None,
                            },
                            generic_arg: None,
                        },
                    },
                    false,
                ),
                (
                    TypeGroupname {
                        ge: TypeGroupnameEntry {
                            occur: None,
                            name: Identifier {
                                ident: "float",
                                socket: None,
                            },
                            generic_arg: None,
                        },
                    },
                    false,
                ),
            ],
        },
    ],
}
```

**Comment by anweiss** [comment]
hey @ericseppanen ... I just cut a `0.5.3` release that should fix this and some other issues that were occurring with inline groups, nested groups and parenthesized types. Let me know if that release is still causing you problems. Cheers!

**Comment by ericseppanen** [comment]
The same problem exists with 0.5.3.

If you dump the ast for the cddl input `"thing = (int / float)"`, and then try replacing the slash with a comma, you will see that the two outputs are basically identical.

**Comment by anweiss** [comment]
Hmm, ok. Let me see what I can do to fix it. I think I know where the problem is

**Comment by anweiss** [comment]
@ericseppanen `0.5.4` has been published and should address this issue. Thanks for reporting.

**Comment by ericseppanen** [comment]
I verified that `0.5.4` works for me.
