### ISSUE TITLE
unwrapping doesn't work as expected

### ISSUE THREAD

**Issue by jonnycrunch** [anweiss/cddl#65]
I'm getting conflicting results of 'valid' cddl from the [gem](https://rubygems.org/gems/cddl/versions/0.8.8) implementation of cddl and this one.   The following example fails to validate using your rust CDDL tool but does using the gem tool. The following CDDL is used to validate a JSON-LD document where the value of the `@context` is either a sting or an array of items where the first item as stated below followed by one or more `URIs`.     My understanding was the `~` is used to [unwrap](https://tools.ietf.org/html/rfc8610#section-3.7) the type and remove the necessary CBOR tag (32).   
```
document = {
  @context : "https://www.example.com/ns/v1" / [ "https://www.example.com/ns/v1", 1* ~uri ]
}
``` 

Thoughts?  Thanks!

**Comment by anweiss** [comment]
Thanks for reporting @jonnycrunch. This is actually not yet implemented :) Will clarify this in the README and get this implemented.

**Comment by anweiss** [comment]
Hey @jonnycrunch, would you be able to share links to the complete CDDL and sample JSON-LD document you're attempting to validate? Thanks!

**Comment by jonnycrunch** [comment]
@anweiss sure.  I am working on the Decentralized Identifiers spec [here](https://github.com/w3c/did-spec-registries/pull/138).  All examples are [here](https://ipfs.io/ipfs/Qmc9Zf5WigJQ7gcxHqpZZDcwMpFur5c5fSEhSykmWipPUH).  Any help validating my approach with CDDL is welcome!   Thanks!

**Comment by anweiss** [comment]
Oh awesome! I've actually happen to have taken a keen interest in DID and SSIs as of late so this is perfect! Will review and get some tests going based on these examples.
