### ISSUE TITLE
Replace serde_cbor

### ISSUE THREAD

**Issue by anweiss** [anweiss/cddl#91]
Given that https://github.com/pyfisch/cbor has been archived and is no longer being maintained, and due to issues such as #90, this issue will ensure a proper CBOR replacement library is implemented.

**Comment by anweiss** [comment]
Will need to wait for https://github.com/enarx/ciborium/issues/22 to publish a new version of this crate with ciborium.

**Comment by Anrock** [comment]
@anweiss blocker seem to be resolved, time for new version?

**Comment by anweiss** [comment]
@Anrock [0.9.0-beta.1](https://github.com/anweiss/cddl/releases/tag/0.9.0-beta.1) has been published. Closing.
